### ISSUE TITLE
Releasing fails out-of-the-box (relasing to GitHub)

### ISSUE THREAD

**Issue by tpetricek** [fsprojects/ProjectScaffold#129]
I just tried using ProjectScaffold on a new project and `build Release` (auto-generated with no changes) fails - I suspect this is in the "release to github" stage of the `Release` target. The log is:

```
git.exe tag 0.0.1-beta
Username for 'https://github.com': tpetricek
Password for 'https://tpetricek@github.com':
Counting objects: 11, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 654 bytes | 0 bytes/s, done.
Total 6 (delta 3), reused 0 (delta 0)
To https://github.com/tpetricek/FnuPlot.git
 * [new tag]         0.0.1-beta -> 0.0.1-beta
Running build failed.
Error:
System.ArgumentException: String cannot be empty
Parameter name: login
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at Fake.TargetHelper.runTarget@317(String targetName) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 331
```

I suspect this is happening because I didn't explicitly specify user name / password when calling `build Release`. But is there a way to make the build script ask for those?

/cc @forki - I think you added this bit of the build script.

**Comment by ovatsus** [comment]
I solved the same problem in FSharp.Data with a simple ReadLine:

https://github.com/fsharp/FSharp.Data/commit/a85c9850f57a6fe7c7f2876c964b998f8ac72dc5#diff-6074983490330a0aac1bd23c958232d7R226
