### ISSUE TITLE
GenerateHelp : error FS0192: internal error: null: GetTRefType

### ISSUE THREAD

**Issue by evilz** [fsprojects/ProjectScaffold#172]
Cannot generate help from blank copy of ProjectScaffold,
Any idea ??
Thank

``` shell
The resulting target order is:
 - CleanDocs
 - GenerateHelp
 - KeepRunning
Starting Target: CleanDocs
Deleting contents of docs/output
Finished Target: CleanDocs
Starting Target: GenerateHelp (==> CleanDocs)
Deleting C:\Users\Vincent\Documents\GITHUB\ProjectScaffold - Copy\docs\content\release-notes.md
Deleting C:\Users\Vincent\Documents\GITHUB\ProjectScaffold - Copy\docs\content\license.md


error FS0192: internal error: null: GetTRefType
Running build failed.
Error:
System.Exception: generating help documentation failed
   at FSI_0001.Build.generateHelp'(Boolean fail, Boolean debug) in C:\Users\Vincent\Documents\GITHUB\ProjectScaffold - C
opy\build.fsx:line 191
   at FSI_0001.Build.clo@198-16.Invoke(Unit _arg1) in C:\Users\Vincent\Documents\GITHUB\ProjectScaffold - Copy\build.fsx
:line 207
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 41
1

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target      Duration
------      --------
CleanDocs   00:00:00.0019323
Total:      00:00:02.6451148
Status:     Failure
---------------------------------------------------------------------
  1) System.Exception: generating help documentation failed
   at FSI_0001.Build.generateHelp'(Boolean fail, Boolean debug) in C:\Users\Vincent\Documents\GITHUB\ProjectScaffold - C
opy\build.fsx:line 191
   at FSI_0001.Build.clo@198-16.Invoke(Unit _arg1) in C:\Users\Vincent\Documents\GITHUB\ProjectScaffold - Copy\build.fsx
:line 207
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 41
1
---------------------------------------------------------------------
```

**Comment by dsyme** [comment]
This error message has been improved in recent release of F#, it's an external issue
