### ISSUE TITLE
Octokit.NotFoundException

### ISSUE THREAD

**Issue by halcwb** [fsprojects/ProjectScaffold#254]
### Description

Using the scaffold setup I want run the release target. Everything runs until the very last step, I then get a 'very helpful' `Octokit.NotFoundException`. 

### Repro steps

Please provide the steps required to reproduce the problem

1. Clone my repository: https://github.com/halcwb/GenUnits.git

2. Update the release notes with a dummy release and run the release target.

### Expected behavior

Please provide a description of the behavior you expect.

### Actual behavior

The following error message:

> Running build failed.
> Error:
> System.AggregateException: One or more errors occurred. ---> Octokit.NotFoundExc
> eption: Not Found
>    at Octokit.Connection.HandleErrors(IResponse response) in C:\Users\shiftkey\D
> ocuments\GitHub\octokit.net\Octokit\Http\Connection.cs:line 570
>    at Octokit.Connection.<RunRequest>d__52.MoveNext() in C:\Users\shiftkey\Docum
> ents\GitHub\octokit.net\Octokit\Http\Connection.cs:line 552
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
> ification(Task task)
>    at Octokit.Connection.<Run>d__51`1.MoveNext() in C:\Users\shiftkey\Documents\
> GitHub\octokit.net\Octokit\Http\Connection.cs:line 537
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
> ification(Task task)
>    at Octokit.ApiConnection.<Post>d__18`1.MoveNext() in C:\Users\shiftkey\Docume
> nts\GitHub\octokit.net\Octokit\Http\ApiConnection.cs:line 0
>    --- End of inner exception stack trace ---
>    at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
>    at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](Cancella
> tionToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
>    at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 com
> putation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
>    at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake
> \src\app\FakeLib\TargetHelper.fs:line 492
> ---> (Inner Exception #0) Octokit.NotFoundException: Not Found
>    at Octokit.Connection.HandleErrors(IResponse response) in C:\Users\shiftkey\D
> ocuments\GitHub\octokit.net\Octokit\Http\Connection.cs:line 570
>    at Octokit.Connection.<RunRequest>d__52.MoveNext() in C:\Users\shiftkey\Docum
> ents\GitHub\octokit.net\Octokit\Http\Connection.cs:line 552
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
> ification(Task task)
>    at Octokit.Connection.<Run>d__51`1.MoveNext() in C:\Users\shiftkey\Documents\
> GitHub\octokit.net\Octokit\Http\Connection.cs:line 537
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
> ification(Task task)
>    at Octokit.ApiConnection.<Post>d__18`1.MoveNext() in C:\Users\shiftkey\Docume
> nts\GitHub\octokit.net\Octokit\Http\ApiConnection.cs:line 0
> -

### Known workarounds

There is a github release and nuget is updated with the newest release. However, I am unsure why I have this error, what it means and/or I can safely ignore it.

### Related information 

* W7
* See build script of my project

**Comment by halcwb** [comment]
I think I provided the wrong credentials. But the error message is totally unhelpful in this.

**Comment by halcwb** [comment]
Well I am at a loss, I checked my github credentials and used the setup as recommended in the documentation with a `release.cmd` file specifying the nuget key and github credentials. But still getting the above error.

**Comment by halcwb** [comment]
Argh, I appended the gitname with ".git" but should have used the name without the extension. My mistake.
