### ISSUE TITLE
Check whether net35 is installed

### ISSUE THREAD

**Issue by auduchinok** [fsprojects/ProjectScaffold#256]
`build.cmd` fails on tests when trying to initialize an empty project if `.Net 3.5` is not installed.
Possible workaround is to try launching anything that needs the framework before doing anything else which will lead to Windows asking to install the framework.

```
1) Fake.UnitTestCommon+FailedTestsException: NUnit test failed. Process finished with exit code FatalError (-2146232576).
   at Fake.NUnitSequential.NUnit(FSharpFunc`2 setParams, IEnumerable`1 assemblies) in C:\code\fake\src\app\FakeLib\UnitTest\NUnit\Sequential.fs:line 45
   at FSI_0005.Build.clo@145-11.Invoke(Unit _arg7) in C:\Users\Eugene\Source\Repos\DotParser\build.fsx:line 146
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 492
```

Reproduced on clean Win10 install with VS 2015 Update 2.
Work fine after `.Net 3.5` install.

**Comment by auduchinok** [comment]
Seems like it may be connected to #241.

**Comment by dsyme** [comment]
It's working for me without .NET 3.5 installed.  Adding AutoGenerateBindingRedirects may have done the trick
