### ISSUE TITLE
Access to the path 'FSharp.ProjectTemplate' is denied.

### ISSUE THREAD

**Issue by yan0lovesha** [fsprojects/ProjectScaffold#311]
### Description

Got error when execute build.cmd on a new project.

### Repro steps

Please provide the steps required to reproduce the problem

1. Open Visual Studio Code.

2. Open an empty folder.

3. Press Ctrl + Shift + p. Input "F#: New Project(ProjectScaffold).

4. Execute builld.cmd after Project created.

5. In the cmd window. Input necessary information when the script asked.

### Expected behavior

The build.cmd executed without errors.

### Actual behavior

Errors:
FsiEvaluationException:

Error: System.IO.IOException: Access to the path 'FSharp.ProjectTemplate' is denied.
           at System.IO.DirectoryInfo.MoveTo(String destDirName)
           at FSI_0005.Init.clo@167-5.Invoke(DirectoryInfo d) in D:\Repo\TMobileBill\init.fsx:line 167
           at FSI_0005.Init.clo@158-2.Invoke(DirectoryInfo pd) in D:\Repo\TMobileBill\init.fsx:line 167
           at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList`1 x)
           at Microsoft.FSharp.Collections.ListModule.Iterate[T](FSharpFunc`2 action, FSharpList`1 list)
           at <StartupCode$FSI_0005>.$FSI_0005_Init$fsx.main@() in D:\Repo\TMobileBill\init.fsx:line 158
        Stopped due to error

### Known workarounds

Please provide a description of any known workarounds.

### Related information 

* Operating system: Windows 10
* Branch
* .NET Runtime, CoreCLR or Mono Version
* Performance information, links to performance testing scripts

**Comment by EHotwagner** [comment]
I experience the same problem.

**Comment by DavidSSL** [comment]
Ok I've been able to reproduce this problem and have also got a workaround.

Effectively, if you run this while the "project" is open in Visual Studio Code, the latter locks 'FSharp.ProjectTemplate', hence why you get the error.

The workaround is to close Visual Studio Code and then run "build.cmd"

**Comment by jackfoxy** [comment]
Closing. The path gets renamed during the init build.
